### PR TITLE
trezor: Enable processing of OP_RETURN outputs

### PR DESCRIPTION
**Pull request by prusnak**
Fixes https://github.com/bitcoin-core/HWI/issues/391

Would it be possible to add PSBT with OP_RETURN to the test suite, so we'll have this case covered?

### CODE REVIEW

**Comment by prusnak** [comment]
@brianddk can you please test this whether this fixes https://github.com/bitcoin-core/HWI/issues/391 for you?

**Comment by achow101** [comment]
Here is a patch for a test case.

```patch
From 00cc8c81b7a0880221306db23584c291d4388afa Mon Sep 17 00:00:00 2001
From: Andrew Chow <achow101-github@achow101.com>
Date: Sun, 31 Jan 2021 14:56:27 -0500
Subject: [PATCH] test OP_RETURN outputs in psbts

---
 test/test_device.py | 19 ++++++++++++++-----
 1 file changed, 14 insertions(+), 5 deletions(-)

diff --git a/test/test_device.py b/test/test_device.py
index 5c5aff1..785f837 100644
--- a/test/test_device.py
+++ b/test/test_device.py
@@ -354,7 +354,7 @@ class TestSignTx(DeviceTestCase):
 
         return sh_desc, sh_ms_info["address"], sh_wsh_desc, sh_wsh_ms_info["address"], wsh_desc, wsh_ms_info["address"]
 
-    def _test_signtx(self, input_type, multisig, external):
+    def _test_signtx(self, input_type, multisig, external, op_return: bool):
         # Import some keys to the watch only wallet and send coins to them
         keypool_desc = self.do_command(self.dev_args + ['getkeypool', '--all', '30', '50'])
         import_result = self.wrpc.importdescriptors(keypool_desc)
@@ -404,7 +404,14 @@ class TestSignTx(DeviceTestCase):
                 self.assertEqual((i + 1) * in_amt, self.wrpc.getbalance("*", 0, True))
                 change_addr = self.wpk_rpc.getrawchangeaddress()
             out_val = (i + 1) * out_amt
-            psbt = self.wrpc.walletcreatefundedpsbt([], [{self.wpk_rpc.getnewaddress('', 'legacy'): out_val}, {self.wpk_rpc.getnewaddress('', 'p2sh-segwit'): out_val}, {self.wpk_rpc.getnewaddress('', 'bech32'): out_val}], 0, {'includeWatching': True, "changePosition": 3, "changeAddress": change_addr}, True)
+            outputs = [
+                {self.wpk_rpc.getnewaddress('', 'legacy'): out_val},
+                {self.wpk_rpc.getnewaddress('', 'p2sh-segwit'): out_val},
+                {self.wpk_rpc.getnewaddress('', 'bech32'): out_val}
+            ]
+            if op_return:
+                outputs.append({"data": "000102030405060708090a0b0c0d0e0f10111213141516171819101a1b1c1d1e1f"})
+            psbt = self.wrpc.walletcreatefundedpsbt([], outputs, 0, {'includeWatching': True, "changePosition": 3, "changeAddress": change_addr}, True)
 
             if external:
                 # Sign with unknown inputs in two steps
@@ -420,15 +427,17 @@ class TestSignTx(DeviceTestCase):
         supports_mixed = {'coldcard', 'trezor_1', 'digitalbitbox', 'keepkey', 'trezor_t'}
         supports_multisig = {'ledger', 'trezor_1', 'digitalbitbox', 'keepkey', 'coldcard', 'trezor_t'}
         supports_external = {'ledger', 'trezor_1', 'digitalbitbox', 'keepkey', 'coldcard', 'trezor_t'}
+        supports_op_return = {"ledger", "digitalbitbox", "trezor_1", "trezor_t", "keepkey"}
         multisig = self.full_type in supports_multisig
         external = self.full_type in supports_external
+        op_return = self.full_type in supports_op_return
         with self.subTest(addrtype="legacy", multisig=multisig, external=external):
-            self._test_signtx("legacy", multisig, external)
+            self._test_signtx("legacy", multisig, external, op_return)
         with self.subTest(addrtype="segwit", multisig=multisig, external=external):
-            self._test_signtx("segwit", multisig, external)
+            self._test_signtx("segwit", multisig, external, op_return)
         if self.full_type in supports_mixed:
             with self.subTest(addrtype="all", multisig=multisig, external=external):
-                self._test_signtx("all", multisig, external)
+                self._test_signtx("all", multisig, external, op_return)
 
     # Make a huge transaction which might cause some problems with different interfaces
     def test_big_tx(self):
-- 
2.30.0

```

**Comment by prusnak** [comment]
> Here is a patch for a test case.

Thanks, applied in 22598ce50e6cb16e32f003572965eb51b077519e

Added one more commit that moves `SUPPORTS_*` closer together

**Comment by achow101** [comment]
ACK 6403389084e26519e3ac0edea7302654283678db

**Pull request merged**
