### PR TITLE
Give Not Initialized error an error code

### LINKED ISSUE #216: Wiped TrezorT enumerate has no error code
I am using the binary provided here: https://github.com/bitcoin-core/HWI/pull/212#issuecomment-510995089

So I think this PR is included there: https://github.com/bitcoin-core/HWI/pull/181

## How to reproduce?

1. Wipe TrezorT
2. Do `hwi enumerate`

Output will be:

`[{"type": "trezor", "path": "webusb:001:4", "needs_pin_sent": false, "needs_passphrase_sent": false, "error": "Not initialized"}]`

Where the error code is missing.

### PR DESCRIPTION
**Pull request by achow101**
Adds a DEVICE_NOT_INITIALIZED error code and gives it in `enumerate` output when devices are not initialized.

Fixes #216

### CODE REVIEW

**Comment by nopara73** [comment]
Concept ACK (I gave the same name to it when I started filling out the wholes in my test suite.)

**Comment by instagibbs** [comment]
needs rebase

**Comment by achow101** [comment]
Rebased

**Comment by jb55** [comment]
Code review ACK cccaec2cc05a6a1010474ee8706bb1c2bc97f4e3

**Pull request merged**
