### PR TITLE
run_tests: fix coldcard path

### PR DESCRIPTION
**Pull request by brunoerg**
https://github.com/Coldcard/firmware/commit/65b652a6f4c74864cb8e1714e0870c1c6e46e454

### CODE REVIEW

**Comment by hebasto** [comment]
Maybe temporarily rebase this PR on top of #752, to properly test it in the CI?

**Comment by brunoerg** [comment]
> Maybe temporarily rebase this PR on top of https://github.com/bitcoin-core/HWI/pull/752, to properly test it in the CI?

Done.

**Comment by brunoerg** [comment]
Rebased

**Comment by achow101** [comment]
ACK 244536f681abb6b4bb7035d59f0bf21f315a130b

**Review by Thompson1985 — APPROVED** [review]

**Pull request merged**
