### PR TITLE
PSBT: also parse and serialize PSBT_GLOBAL_XPUB

### PR DESCRIPTION
**Pull request by benma**
Needed for BitBox02 to check and perform the xpubs registration.

Extracted from #407 according to this comment: https://github.com/bitcoin-core/HWI/pull/407#issuecomment-768513068

### CODE REVIEW

**Comment by instagibbs** [comment]
could we get a single example for `test/data/test_psbt.json` to prove out the round-trip serialization?

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin-core/HWI/pull/437/commits/49576db9700e55ebb0d05f4bf146afa9987ac304

test would be 👌

**Comment by achow101** [comment]
Concept ACK. I would also like for a test to be added.

**Comment by benma** [comment]
@instagibbs @achow101 I added a positive and a negative test containing xpubs.

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin-core/HWI/pull/437/commits/d3d9fc93418533afe92984e94264a4f6140f011c

**Comment by achow101** [comment]
ACK d3d9fc93418533afe92984e94264a4f6140f011c

**Pull request merged**
