### PR TITLE
trezor: add Trezor Safe 5 support

### PR DESCRIPTION
**Pull request by matejcik**
just updated definitions from upstream trezorlib

### CODE REVIEW

**Comment by prusnak** [comment]
CI build failures are reported here https://github.com/trezor/trezor-firmware/issues/3988 but the changes look good to me!

**Review by prusnak — APPROVED** [review]
CI build failures are reported here https://github.com/trezor/trezor-firmware/issues/3988 but the changes look good to me!

**Comment by matejcik** [comment]
let's see if https://github.com/bitcoin-core/HWI/pull/742/commits/e114031f48b639119ff79391890553f654c0573a helps

**Comment by prusnak** [comment]
> let's see if [e114031](https://github.com/bitcoin-core/HWI/commit/e114031f48b639119ff79391890553f654c0573a) helps

It did, nice!

**Comment by craigraw** [comment]
Tested this successfully with all related functions on Sparrow.

**Comment by prusnak** [comment]
@achow101 Hi! Can we have a merge of this PR and then a new release? Lots of third parties are waiting for this

**Comment by matejcik** [comment]
heads-up: during today i'll update the PR with a new model. Ideally I'll also try to fit in a "generic unrecognized Trezor" support.

**Comment by achow101** [comment]
ACK 3f91b357dc98c26636fc45a5f57353c09ae49775

Did not test, but looks fine.

**Comment by zikziko** [comment]
Hey, do we have any update on the potential release of the new HWI version including this change? I think many people would benefit, including me, so we can finally use the new Trezor with Sparrow and other wallets.

**Pull request merged**
