### PR TITLE
Create internal and external keypools by default

### PR DESCRIPTION
**Pull request by instagibbs**
Returns both internal an external chains when `--path` and `--internal` are not given as arguments.

### CODE REVIEW

**Comment by instagibbs** [comment]
@Sjors @achow101 concept ACKs?

**Comment by achow101** [comment]
Concept ACK

**Comment by Sjors** [comment]
Concept ACK, but do fix the tests :-)

**Comment by achow101** [comment]
Fix tests?

**Comment by instagibbs** [comment]
rebased, I have to first make sure ledger tests are passing for master then I'll fix tests

**Comment by instagibbs** [comment]
Looks like I got it working properly.

@achow101 review ready

**Comment by achow101** [comment]
ACK b1b7212d39b378babfa0a0540189bc8f71f1efbd

**Pull request merged**
