### PR TITLE
Replace dead "bytes_to_hex_str" with "binascii.hexlify"

### LINKED ISSUE #219: `bytes_to_hex_str` not imported in `serializations.py`
`bytes_to_hex_str` is used [here](https://github.com/bitcoin-core/HWI/blob/master/hwilib/serializations.py#L239) and [here](https://github.com/bitcoin-core/HWI/blob/master/hwilib/serializations.py#L290) but doesn't exist as far as I can tell, causing a `NameError` if either `__repr__` is ever exercised

### PR DESCRIPTION
**Pull request by justinmoon**
Fixes #219

### CODE REVIEW

**Comment by instagibbs** [comment]
`.hex()` not usable instead? minimum python version is enough for it.

**Comment by justinmoon** [comment]
I used `binascii` because it was used elsewhere in the file. Updated to use `.hex()`!

**Comment by achow101** [comment]
Please squash

**Comment by achow101** [comment]
Code review ACK bccf63288ba485e2a331dc4170b0e14233ecf53d

**Pull request merged**
