### PR TITLE
pin poetry version to 0.12.12 as 0.12.14 is broken

### PR DESCRIPTION
**Pull request by achow101**
The latest version of poetry (0.12.14) is broken which is causing travis to fail. Pin the version to 0.12.13 for now.

### CODE REVIEW

**Comment by achow101** [comment]
This will be merged when travis passes.

**Comment by instagibbs** [comment]
like, poetry itself or some versioning difference with breaking change?

**Comment by achow101** [comment]
> like, poetry itself or some versioning difference with breaking change?

poetry 0.12.14 itself is broken.

**Comment by achow101** [comment]
Downgrading further to 0.12.12 as apparently 0.12.13 has a bug where the script isn't added to the path in the poetry virtualenv.

**Pull request merged**
