### PR TITLE
Expose app name of ledger devices

### PR DESCRIPTION
**Pull request by promag**
Requirement for #158.

### CODE REVIEW

**Comment by achow101** [comment]
I'm not sure that it is useful to expose this information. I think it would be better if we just didn't enumerate a device if it wasn't in the Bitcoin or Bitcoin Testnet apps.

**Comment by promag** [comment]
@achow101 ok, so just ensure app matches the command network and fail otherwise?

**Comment by achow101** [comment]
For mainnet, make sure it only matches "Bitcoin". For testnet, I think it should match both "Bitcoin" and "Bitcoin Test" (for testing, sometimes it's easier to just use the mainnet app with `--testnet`).

**Comment by instagibbs** [comment]
I wouldn't mind it throwing an error if the app name isn't what's expected. Right now it's semi mysterious at points.

**Comment by achow101** [comment]
Superseded by #473

**Pull request closed without merging**
