### PR TITLE
Bump Python patch version to 3.6.12

### PR DESCRIPTION
**Pull request by Sjors**
It's a pain on macOS Big Sur to run older patch versions, because PyEnv can't install them anymore.

### CODE REVIEW

**Comment by achow101** [comment]
It looks like the wine_builder job is failing since python.org doesn't upload windows installer binaries for releases in the security fix only part of the lifecycle.

**Comment by Sjors** [comment]
Maybe I should keep the original windows version?

**Comment by achow101** [comment]
> Maybe I should keep the original windows version?

Yes

**Comment by achow101** [comment]
ACK c8fd9fecaf3a25e71b355d567019e7705f7b6102

**Pull request merged**
