### PR TITLE
Provide error codes in enumerate output

### PR DESCRIPTION
**Pull request by achow101**
Adds error codes to `enumerate`'s output as suggested here: https://github.com/bitcoin-core/HWI/pull/175#discussion_r286126395

### CODE REVIEW

**Comment by nopara73** [comment]
I'm not a Python dev, but LGTM and straightforward.

**Comment by jb55** [comment]
looks like a bunch of code duplication, could there a be an error handler util? ie:

```py
def handle_errors(res, fn):
    try:
        fn()
    except HWWError as e:
        res['error'] = "Could not open client or get fingerprint information: " + e.get_msg()
        res['code'] = e.get_code()
    except Exception as e:
        res['error'] = "Could not open client or get fingerprint information: " + str(e)
        res['code'] = UNKNOWN_ERROR
    return res

if __name__ == "__main__":
    data = {}

    def process():
        raise Exception("oh no")

    res = handle_errors(data, process)
    print(res)
```

**Comment by achow101** [comment]
> looks like a bunch of code duplication, could there a be an error handler util?

Probably, but I think we can do that later. It would require rearranging quite a bit of the enumeration code which would make this more difficult to review.

**Comment by jb55** [comment]
@achow101 you mind if I take a stab at it?

**Comment by achow101** [comment]
Go ahead

**Comment by jb55** [comment]
apparently it can be done quite elegantly with contextmanager + with blocks. TIL. here's a first sketch:

https://github.com/bitcoin-core/HWI/compare/26b8808c3b9573fd759cee2e04fed6fadb10005e~2..26b8808c3b9573fd759cee2e04fed6fadb10005e

will PR soon

**Pull request merged**
