### PR TITLE
Print default values in help

### PR DESCRIPTION
**Pull request by achow101**
Changes the help text formatter to one that also prints out the default values.

There is unfortunately no combined `RawDescriptionHelpFormatter` (the current formatter we use) and `ArgumentDefaultsHelpFormatter` (the formatter which will print arguments) so instead I made a custom formatter that combines both by subclassing both formatters. This formatter is then set as `HWIArgumentParser`'s `formatter_class` so that the main help text and the command help texts use that formatter.

### CODE REVIEW

**Comment by instagibbs** [comment]
Probably should go through the various output and make sure you don't get weird duplication like:

```
 ./hwi.py getkeypool --help
usage: hwi.py getkeypool [-h] [--keypool] [--internal] [--sh_wpkh] [--wpkh]
                         [--account ACCOUNT] [--path PATH]
                         start end

positional arguments:
  start              The index to start at.
  end                The index to end at.

optional arguments:
  -h, --help         show this help message and exit
  --keypool          Indicates that the keys are to be imported to the keypool
                     (default: False)
  --internal         Indicates that the keys are change keys (default: False)
  --sh_wpkh          Generate p2sh-nested segwit addresses (default path:
                     m/49h/0h/0h/[0,1]/*) (default: False)
  --wpkh             Generate bech32 addresses (default path:
                     m/84h/0h/0h/[0,1]/*) (default: False)
  --account ACCOUNT  BIP43 account (default: 0) (default: 0)
  --path PATH        Derivation path, default follows BIP43 convention, e.g.
                     m/84h/0h/0h/1/* with --wpkh --internal. If this argument
                     and --internal is not given, both internal and external
                     keypools will be returned. (default: None)
```

**Comment by nopara73** [comment]
Concept ACK

**Comment by achow101** [comment]
> Probably should go through the various output and make sure you don't get weird duplication like for account, --sh_wpkh, --wpkh:

Done

**Comment by instagibbs** [comment]
> $ flake8
./hwilib/cli.py:141:89: E999 SyntaxError: EOL while scanning string literal

**Comment by instagibbs** [comment]
tACK https://github.com/bitcoin-core/HWI/pull/256/commits/eefd1f48535db16b4ec2fce0279a574405ea5d22

**Pull request merged**
