### PR TITLE
List udev rules for improved readibility

### PR DESCRIPTION
**Pull request by sam-sla**

### CODE REVIEW

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin-core/HWI/pull/272/commits/dd4034df2ae2deaeca7f8517186e4d2ed1ceac39

**Comment by instagibbs** [comment]
unsure why Travis isn't running, doesn't seem to have blacklisted this repo again

**Comment by achow101** [comment]
ACK dd4034df2ae2deaeca7f8517186e4d2ed1ceac39

> unsure why Travis isn't running, doesn't seem to have blacklisted this repo again

Not like it matters, just a doc change.

**Comment by sam-sla** [comment]
:smile:

**Pull request merged**
