### PR TITLE
Improve error handle for `Ledger` devices

### PR DESCRIPTION
**Pull request by brunoerg**
Discovered it while reviewing [#bitcoin/24313](https://github.com/bitcoin/bitcoin/pull/24313). The `ledger_exception` function was not dealing with `ApduException` exceptions. It's basically similar to `BTChipException` and we can use its "error code" to return friendly error messages. 

e.g for `displayaddress`: 

**before**:
`{"error": "Exception: invalid status 0x6985", "code": -13}`
**after**:
`{"error": "display_singlesig_address canceled", "code": -14}`

### CODE REVIEW

**Comment by brunoerg** [comment]
cc: @Sjors

**Comment by Sjors** [comment]
@bigspider is there a complete list of (Bitcoin app) error codes published somewhere?

**Comment by bigspider** [comment]
> @bigspider is there a complete list of (Bitcoin app) error codes published somewhere?

[This mapping](https://github.com/LedgerHQ/app-bitcoin-new/blob/d6b3f56bb0957c55a127c250074028d1d4d125c7/bitcoin_client/ledger_bitcoin/exception/device_exception.py#L9-L21) is currently as good as it gets. The `IncorrectDataError` (SW `0x6A80`) is the most common error and it's returned for way too many distinct error situations; hopefully I find some time to improve it with more fine-grained error results.

**Comment by achow101** [comment]
ACK 0d5412a7ea6a2f4043d2bccfd4e0957caffba65f

**Comment by bigspider** [comment]
> 0x5515 is what I get when the app is in screensaver mode (Ledger Nano X, BTC app 2.1.3)

Indeed, that situation used to be managed by the app directly, while now it's handled in the app sdk, so the error code changed. I'll add the error code to the client libraries, thanks!

**Pull request merged**
