### PR TITLE
Add getdescriptors command

### PR DESCRIPTION
**Pull request by Sjors**
Returns all relevant descriptors for a given account, e.g.:

```sh
./hwi.py --fingerprint 00000000 getdescriptors --account 0
```

```json
{
  "receive": [
    "pkh([00000000/44h/0h/0h]xpub6C.../0/*)#fn95jwmg",
    "sh(wpkh([00000000/49h/0h/0h]xpub6B..../0/*))#j4r9hntt",
    "wpkh([00000000/84h/0h/0h]xpub6C.../0/*)#qw72dxa9"
  ],
  "internal": [
    "pkh([00000000/44h/0h/0h]xpub6C.../1/*)#c8q40mts",
    "sh(wpkh([00000000/49h/0h/0h]xpub6B..../1/*))#85dn0v75",
    "wpkh([00000000/84h/0h/0h]xpub6C..../1/*)#36mtsnda"
  ]
}
```

### CODE REVIEW

**Comment by Sjors** [comment]
Rebased and added an xpub cache so we don't fetch the same xpub twice from a device for internal and change descriptors.

**Comment by Sjors** [comment]
Rebased after #135.

**Comment by achow101** [comment]
Tested ACK b0c6cd77516c03e754a86166c7f28254473ddb50

**Comment by prusnak** [comment]
Nice!

**Pull request merged**
