### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Review by prusnak — APPROVED** [review]
ACK d12c1d01462f0cc019e894401c68dbed5e8e8fd4

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin-core/HWI/pull/563/commits/d12c1d01462f0cc019e894401c68dbed5e8e8fd4

**Comment by prusnak** [comment]
> Please remove those changes.

This particular change is fine, because it actually fixes a bug present only in HWI code. The upstream code does not have this typo:

https://github.com/bitcoin-core/HWI/pull/563/files#diff-a992f7a6b602dced576966694956a427b08a94c7f3a73923042e46dab84bb797L181-R181

**Comment by rex4539** [comment]
Reverted the aforementioned cases.

**Comment by achow101** [comment]
ACK 7ff8596abe46e52f0bab5eeaefdc6ea8a514dec1

**Pull request merged**
