### PR TITLE
commands.py: use fingerprint if already captured by client

### PR DESCRIPTION
**Pull request by peter-conalgo**
For me with a `signmessage` to the Coldcard simulator, this saves 6-7 seconds. But this should speed up all devices, since they are already capturing the fingerprint value into the enumeration information.

### CODE REVIEW

**Comment by peter-conalgo** [comment]
- this PR is independent of PR #162 but complements it

**Comment by instagibbs** [comment]
light tACK on ledger with various commands. Seems 50% faster or so for commands like `signmessage` from eyeballing.

**Comment by instagibbs** [comment]
poetry builds failing:

```
[AttributeError]                  
'NullIO' object has no attribute 'write_line'  
                                                 
install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
The command "poetry install" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by achow101** [comment]
> poetry builds failing:

That's a problem with poetry. See #164

**Comment by achow101** [comment]
Closing and reopening to retrigger travis.

**Comment by achow101** [comment]
ACK 0cf6bb99980aa9913f898cb94db8bbae63b5c42d

**Comment by Sjors** [comment]
Inspired by this I added an xpub cache in #137.

**Pull request merged**
