### PR TITLE
Add option to enter commands over stdin

### PR DESCRIPTION
**Pull request by achow101**
This PR adds a `--stdin` option which allows arguments to be entered over stdin in a way similar to bitcoin-cli's `--stdin` option.

Built on #125 and to test the `stdin` interface

### CODE REVIEW

**Comment by Sjors** [comment]
Can you give some usage examples? Do you have to enter all arguments this way, or can do something like: `cat psbt > hwi.py --fingerprint=... signtransaction`?

**Comment by achow101** [comment]
You can do it mixed. You just need to have the arguments entered in the order as if they were entered on the command line.

**Comment by instagibbs** [comment]
needs rebase

**Comment by achow101** [comment]
Rebased

**Comment by instagibbs** [comment]
needs rebase again

**Comment by achow101** [comment]
Rebased

**Comment by instagibbs** [comment]
So this is only supposed to work on commands and the comman's arguments, right? Not path, type, etc.

**Comment by instagibbs** [comment]
light tACK https://github.com/bitcoin-core/HWI/pull/126/commits/49bc7fa5dab02668c8a8b33cc4b6932acf688110

**Comment by achow101** [comment]
> So this is only supposed to work on commands and the comman's arguments, right? Not path, type, etc.

It should work with all arguments, including path, type, etc.

**Comment by instagibbs** [comment]
ah nevermind, was entering the other options in incorrectly.

re-tACK https://github.com/bitcoin-core/HWI/commit/49bc7fa5dab02668c8a8b33cc4b6932acf688110

**Comment by Sjors** [comment]
Post merge ACK. We should document how to use this...

E.g. this works:
```sh
echo "signtx PSBT" | ./hwi.py --fingerprint 00000000 --stdin
```

But this throws an error:
```sh
echo "PSBT" | ./hwi.py --fingerprint 00000000 --stdin signtx
```

I updated https://github.com/bitcoin/bitcoin/pull/14912 to use `--stdin` for the PSBT, since that could be quite long.

**Comment by instagibbs** [comment]
@Sjors what error are you getting?

**Comment by Sjors** [comment]
Some argument parse error. But I just tried again and now it's happy, so maybe I did something else wrong.

**Comment by instagibbs** [comment]
Seems like a common thread here :)

**Pull request merged**
