### PR TITLE
bump typing-extensions dependency

### PR DESCRIPTION
**Pull request by k9ert**
Upgrade typing-extensions dependency ( #572)

I chose not the most recent one but try to also be uptodate.
image

### CODE REVIEW

**Comment by achow101** [comment]
Please run `poetry lock` and commit the changes it makes.

**Comment by k9ert** [comment]
Should i make some stats on the number of tests failing and then try how to minimize them with a version `>4.0`?
Or any idea how i can help with this?

**Comment by achow101** [comment]
Some of the tests are issues with issues with the tests themselves with timing out (usually they're the ledger tests). These you can ignore. The others appear to be due to this change. The type checker needs to be passing, and we can't have errors from poetry itself.

**Comment by k9ert** [comment]
Ok, so with typing-extension `4.5` we have 77 failing, 15 cancelled, and 43 successful checks.

**Comment by k9ert** [comment]
With 4.1.0 we have 69 failing, 30 canceled and 36 successfull checks.

**Comment by k9ert** [comment]
With 3.10 we have 86 failing, 30 cancelled, and 19 successful checks

**Comment by achow101** [comment]
FYI I'm going to push a few commits to this PR to try to get it working.

**Comment by achow101** [comment]
I think the issue was just outdated CI caches. Going to merge this now and fix CI in a followup.

**Pull request merged**
