### PR TITLE
ci: Replace Cirrus CI with GitHub Actions

### PR DESCRIPTION
**Pull request by hebasto**
This PR moves tests from Cirrus CI, which [is not free anymore](https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/), to GitHub Actions.

Possible performance improvements (caching, etc.) are left for future follow-ups.

### CODE REVIEW

**Comment by hebasto** [comment]
A GHA run in my personal repo: https://github.com/hebasto/HWI/actions/runs/6111940034.

**Comment by hebasto** [comment]
The following actions are required to be allowed explicitly in "Actions permissions":
```
actions/checkout@*,
actions/download-artifact@*,
actions/upload-artifact@*,
```

**Comment by achow101** [comment]
Cool, thanks for doing this.

Could you also remove the cirrus config?

**Comment by hebasto** [comment]
> Cool, thanks for doing this.
> 
> Could you also remove the cirrus config?

You mean, the entire `.cirrus.yml`, even with tests not ported to GHA yet?

**Comment by achow101** [comment]
> You mean, the entire `.cirrus.yml`, even with tests not ported to GHA yet?

Ah, didn't read it that closely. I would prefer to merge this once everything could be moved instead of doing some on each, especially since the builder tasks end up being duplicated.

**Comment by hebasto** [comment]
> I would prefer to merge this once everything could be moved instead of doing some on each, especially since the builder tasks end up being duplicated.

Done.

**Comment by hebasto** [comment]
In case someone wants to compare CI builds:
- this PR branch on the GHA: https://github.com/hebasto/HWI/actions/runs/6115893263
- the current master branch on the Cirrus CI: https://cirrus-ci.com/github/bitcoin-core/HWI/master

**Comment by hebasto** [comment]
Updated the major version of the `docker/build-push-action`.

See: https://github.com/docker/build-push-action/releases/tag/v5.0.0

**Pull request merged**
