### PR TITLE
psbt serialization fix

### PR DESCRIPTION
**Pull request by stepansnigirev**
unknowns should be in global scope

### CODE REVIEW

**Comment by achow101** [comment]
Hmm. I thought we had a test for this... if not, could you add a test?

**Comment by stepansnigirev** [comment]
Added a test with unknowns. These unknowns are actually not-yet-implemented xpub fields.

**Comment by achow101** [comment]
ACK aff5f57d49afc0637ee521fcd1012a8f48a1d91d

Reviewed code and checked that the test fails on master but not with this PR.

**Comment by nopara73** [comment]
@stepansnigirev would you mind to give me a short description on what this PR was about? I'm mainly interested if this affects Wasabi users or not.

**Comment by stepansnigirev** [comment]
This is mostly related to ColdCard multisignature signing.
If psbt has extra fields in global scope (i.e. cosigner's xpubs) HWI would serialize it incorrectly.
As you are only using single key inputs and don't put any unknown fields to the global scope it doesn't affect your users.

**Comment by instagibbs** [comment]
@stepansnigirev oh you might have some ideas for https://github.com/bitcoin-core/HWI/pull/260 then if you know how it works. Haven't had the time to dive in to figure out how to fix it.

**Pull request merged**
